backend:
  name: github
  repo: tmp/tmp
  branch: master

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

local_backend: true

collections:
  - name: test # Used in routes, e.g., /admin/collections/blog
    label: Test # Used in the UI
    folder: content # The path to the folder where the documents are stored
    path: '{{slug}}/index'
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true
